# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://deborahyalves.github.io/
title: Déborah Alves
email: deborah.yaraalves@gmail.com
author: Deborah Alves
description: > # "Write an awesome description for your new site here. 
  Offering companies a Virtual Assistence to help them get things done.
copyright: 'Copyright &copy; 2015 Déborah Alves. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/d%C3%A9borah-alves-998b41121/
  - title: E-mail
    url: mailto:deborah.yaraalves@gmail.com
